# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ooGrxoh0ozG91i3o6nGXQy8s9fDWXjsa
"""

def min_max_line(filename):
    with open(filename, 'r', encoding='utf-8') as file:
        lines = [line.rstrip('\n') for line in file.readlines()]

    # Ищем самую короткую строку (исключая возможные пустые строки)
    min_line = min([line for line in lines if line], key=len)

    # Ищем самую длинную строку
    max_line = max(lines, key=len)

    return f"Min = '{min_line}', max = '{max_line}'."